### ISSUE TITLE
Examples of using the plugin

### ISSUE THREAD

**Issue by JoeTalbot** [athieriot/drone-artifactory#16]
I am fairly new to drone, and i am struggling with using this plugin, either i can get drone to run successfully but completely skip anything related to the artifactory plugin, or it gives me an obscure error.

For example, if my entire .drone.yml looks like this: 

```
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: https://binrepo.target.com/artifactory
    username: $$USERNAME
    password: $$PASSWORD
    pom: pom.xml
    repo_key: infra-automation-dev
    files:
      - target/*.jar
      - target/*.war
      - dist/**/*.min.js
```

the output of the drone run is:

```
username@80e6500b67fa:MobileAPI-- (joe_artifactory)$ drone exec
Running Matrix job #0
```

if i have my entire .drone.yml file looking like this:

```
pipeline:
  test:
    image: maven:alpine
    commands:
     - mvn --quiet --batch-mode test
     
  publish_war:
    image: maven:alpine
    commands:
      - mvn --batch-mode clean install
  deploy_war:
    plugin:
      artifactory:
        image: athieriot/drone-artifactory
        url: https://binrepo.target.com/artifactory
        username: $$USERNAME
        password: $$PASSWORD
        pom: pom.xml
        force_upload: true
        repo_key: infra-automation-dev
        files:
          - /root/.m2/repository/com/tgt/DEV/maximo-services/1/maximo-services-1.war
```

then everyhting prior to the deploy_war step runs sucessfully. What am i missing?

**Comment by athieriot** [comment]
Hi @JoeTalbot,

First of all, please note that this plugin only supports Drone 0.5 since yesterday so there might still be some mix and match in the documentation between the two config set.

Because you use the pipeline keyword, I'm assuming you are using Drone 0.5, but it seems that you have used Drone 0.4 configuration for drone-artifactory.

At first glance, there is two things I can see that are incorrect:

   - You can remove the "plugin:" line under "deploy_war", it is not necessary anymore since pipeline has been introduced.
   - Secrets are not injected using $$ anymore. I advice you to take a look at this page: https://github.com/athieriot/drone-artifactory/blob/master/DOCS.md which explains how to register secrets with Drone 0.5 and if you do so, you'll be able to remove both "username" and "password"

Please keep us updated on how it goes :)
It might help other people.

**Comment by JoeTalbot** [comment]
@athieriot Thank you for the quick response, i tried that out, and it is still not running anything to do with the plugin? I am running drone 5, and here is my updated drone.yml file.

```
pipeline:
  test:
    image: maven:alpine
    commands:
     - mvn --quiet --batch-mode test
  publish_war:
    image: maven:alpine
    commands:
      - mvn --batch-mode clean install
  deploy_war:
    artifactory:
      image: athieriot/drone-artifactory
      url: https://binrepo.target.com/artifactory
      pom: pom.xml
      force_upload: true
      repo_key: infra-automation-dev/test
      files:
          - /root/.m2/repository/com/tgt/DEV/maximo-services/1/maximo-services-1.war
```
Maybe i am missing something completely, but how does the plugin have access to the war file built in the publish_war step? is that how this is intended to be used, or am i setting something up wrong?

**Comment by athieriot** [comment]
Ah. My bad.
You can get read of the "artifactory:" line as well.

This name use to have a meaning (Pointing out the Docker image to use) but not anymore.

Also, to answer your question, plugins normally share the workspace, so anything built during the previous phases will be accessible later (From the current directory).
Meaning you should probably update the "files" value to be relative. Something like:

      target/maximo-services-1.war

Replacing by the actual name obviously

**Comment by JoeTalbot** [comment]
I updated my drone.yml file to: 
```
pipeline:
  test:
    image: maven:alpine
    commands:
     - mvn --quiet --batch-mode test
  publish_war:
    image: maven:alpine
    commands:
      - mvn --batch-mode clean install
  deploy_war:
    url: https://binrepo.target.com/artifactory
    pom: pom.xml
    force_upload: true
    repo_key: infra-automation-dev/test
    files:
        - target/maximo-services-1.war
```

And it still completes successfully at the publish_war step but does not continue to deploy_war. The confusing part is that I get no errors, and it's hard to start to troubleshoot?

**Comment by athieriot** [comment]
You still need the image name though (In deploy_war section)

    image: athieriot/drone-artifactory

I'll soon be dry of answers and yes, the lack of error message seems problematic but I have good hopes ;) 
(Sure you don't have any logs server side?)

It starting to look good though, you must be close.

**Comment by JoeTalbot** [comment]
I really appreciate the assistance! However I am still running into the same situation, no errors, and it doesn't run past the publish_war step. I will ask internally to see if i can find any more logs beyond what i see on the output of a `drone exec` or the output from our drone server.

**Comment by JoeTalbot** [comment]
I am getting closer, i found someone to help me get the logs off the artifactory server. using this drone.yml:
```

pipeline:
  test:
    image: maven:alpine
    commands:
     - mvn --quiet --batch-mode test
  publish_war:
    image: maven:alpine
    commands:
      - mvn --batch-mode clean install
  deploy_war:
    image: athieriot/drone-artifactory
    url: https://binrepo.target.com/artifactory
    pom: pom.xml
    force_upload: true
    repo_key: /infra-automation-dev/test
    files:
        - target/maximo-services-1.war
```

I get this output in the server logs:
```
2016-11-22 17:00:34,379 [ajp-nio-8009-exec-183] [WARN ] (o.a.w.s.RequestUtils:155) - Request /artifactory/infra-automation-dev/test/com/tgt/DEV/maximo-services/1/maximo-services-1.pom should be a repo request and does not match any repo key
2016-11-22 17:21:37,075 [ajp-nio-8009-exec-177] [WARN ] (o.a.w.s.RequestUtils:155) - Request /artifactory/infra-automation-dev/com/tgt/DEV/maximo-services/1/maximo-services-1.pom should be a repo request and does not match any repo key
2016-11-22 17:36:05,249 [ajp-nio-8009-exec-157] [WARN ] (o.a.w.s.RequestUtils:155) - Request /artifactory//infra-automation-dev/test/com/tgt/DEV/maximo-services/1/maximo-services-1.pom should be a repo request and does not match any repo key
```

im not sure how its determining the repo key, but does something with the settings look goofy?

**Comment by JoeTalbot** [comment]
I am unable to get this to work, I'm going to switch to using a maven artifactory plugin and deploy with maven instead. Thank you for the quick response and offering assistance.

**Comment by JoeTalbot** [comment]
I was able to get this working with a slightly different image for the artifactory plugin section. https://hub.docker.com/r/jmccann/drone-artifactory, and added the latest tag. Also, i had to ensure the repo i was pushing to was actually a maven repo, and I was able to deploy

**Comment by athieriot** [comment]
That's good news.

Funny thing is that @jmccann pushed these changes into my repository a few days ago.
So theoretically you should have been ok with your previous configuration.

**Comment by JoeTalbot** [comment]
I think the main problem is I wasn't using the latest tag with your image, i intend to try that today and see if it works.

**Comment by athieriot** [comment]
There is no other tag though but I did push several times before merging the code.

It might still be a genuine issue.

Thank you for taking the time

**Comment by JoeTalbot** [comment]
Not a problem. I will check it out and see what happens!

**Comment by JoeTalbot** [comment]
I was able to get it to work, i think it was a combination of my understanding, and making sure i had the correct drone secrets in place. Here is the final working drone.yml. 
```

pipeline:
  test:
    image: maven:alpine
    commands:
     - mvn --quiet --batch-mode test
  build_war:
    image: maven:alpine
    commands:
      - mvn --batch-mode clean install
  deploy_war:
    image: athieriot/drone-artifactory:latest
    url: https://binrepo.target.com
    pom: pom.xml
    repo_key: infra-automation-dev
    files:
      - target/*.jar
      - target/*.war
      - dist/**/*.min.js
    when:
      branch: master
```
